version: '3.7'

services:
  app:
    build: .
    container_name: nuxt-app
    restart: always
    ports:
      - '3030:3030'
    command: 'npm run start'

#version: '3.3'
#services:
#  nuxt:
#    build:
#      context: .
#    image: nuxt_dev
#    container_name: nuxt_dev
#    command: npm run dev
#    volumes:
#      - .:/app
#      - /app/node_modules
#    ports:
#      - "3030:3030"
